### ISSUE TITLE
Build our own Windows binaries

### ISSUE THREAD

**Issue by riastradh-brave** [brave/tor_build_scripts#15]
...rather than pulling the Tor Browser's, which lag behind, unless there's a particular reason they lag behind.

Obviates #13 if we get to this first.

**Comment by riastradh-brave** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
@riastradh-brave has been trying with mingw; @jumde and I were trying using MSVC

**Comment by jumde** [comment]
Fixed by: 6f9aba0
