### ISSUE TITLE
Upgrade OpenSSL to 1.1.0

### ISSUE THREAD

**Issue by cretz** [brave/tor_build_scripts#26]
In my static linking scripts, I have found issues with OpenSSL 1.1.0 and Tor's configure scripts, namely that the `-lssl` and `-lcrypto` are in the wrong order on some of the gcc calls to check OpenSSL. I opened [this ticket](https://trac.torproject.org/projects/tor/ticket/26464) but curious what is needed in these scripts to upgrade OpenSSL.

**Comment by tobtoht** [comment]
OpenSSL 1.0.2 is out of support and has at least one high severity vulnerability: https://www.openssl.org/news/secadv/20201208.txt

**Comment by jumde** [comment]
@tobtoht - We are working on a fix for this issue. There is a bug in the tor client code which doesn't allow static linux binaries with OpenSSL 1.1.1. The fix for the issue is expected in tor-4.5 release, which should be released soon.
